# https://taskfile.dev

version: '3'

tasks:
  test:
    desc: "Runs the current go module with the ev3test tag."

    cmds:
      - go run -tags ev3test .

    dir: '{{.USER_WORKING_DIR}}'
  
  build:
    desc: "Builds the current go module for deployment on an EV3."

    vars:
      out: '{{.o | default "main"}}'

    cmds:
      - GOOS=linux GOARCH=arm GOARM=5 go build -o {{.out}} .

    dir: '{{.USER_WORKING_DIR}}'